# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Compartiendo código
email: emanuellpp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este es mi blog personal, aqui estaré compartiendo tutoriales
  sobre desarrollo de software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eparedez.com" # the base hostname & protocol for your site
twitter_username: EParedezm
github_username:  EParedez
layout: default
comments: true

# Build settings
markdown: kramdown
